name = "jdplyr"
uuid = "4b698356-8bd1-11ea-19da-c55a7d14b225"
author = ["Daniel Hopp <daniel.hopp1@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "≥ 0.20.0"
julia = "≥ 1.0.0"
